
export const routes = {
  profile: "/",
  previousSurvey: "/previous-survey",
  postExerciseSurvey: "/post-exercise-survey",
  instruction: "/instruction",
  activeExercise: "/active-exercise",
  exerciseSessionCompleted: "/exercise-session-completed",
  patientHistory: "/patient-history",
  specialistHome: "/specialist-home",
  specialistCalendar: "/spetialis-calendar",
  specialistProfile: "/specialist-profile",
  scheduleAppointment: "/schedule-appointmen",
  patientList: "/patient-list",
  routineList: "/routine-list",
  medicalRecord: "/medical-record",
  registerPatient: "/register-patient",
  adminMain: "/admin-main",
  adminUsers: "/admin-users",
  adminProfile: "/admin-profile",
  createUser: "/create-user",
  exercisesLibrary: "/exercises-library",
  createRutine: "/create-rutine",
};
